### ISSUE TITLE
wlinux-setup not found

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#105]
Hi,
yesterday I have installed the 1.1.21 and have used wlinux-setup to install python, GO and zsh. I have set zsh as default.

Today, if I open WLinux and run wlinux-setup, I have `command not found: wlinux-setup`.

Thank you

# WLinux Version
1.1.21

# Windows Build
10.0.17134.320

**Comment by sirredbeard** [comment]
Is /etc/setup present?
Is /etc/profile present?
Does /etc/profile contain the alias from /etc/setup to wlinux-setup?
Are using a non-standard shell that ignores /etc/profile aliases?

**Comment by aborruso** [comment]
Hi @sirredbeard, first of all I'm using WLinux, without modifying anything.

> Is /etc/setup present?

yes there is this file

> Is /etc/profile present?

No. There is `/etc/profile.d` file

> Does /etc/profile contain the alias from /etc/setup to wlinux-setup?

No, because there is not `/etc/profile` folder

> Are using a non-standard shell that ignores /etc/profile aliases?

I have used `wlinux-setup` to install and set as default zsh.

Thank you

**Comment by sirredbeard** [comment]
Somehow your /etc/profile file got deleted. Weird.

Neither zsh nor python install should alter, let alone remove, /etc/profile.

Installing Go via wlinux-setup should have added two lines to /etc/profile. If it did not exist it would have created the file and then added the two lines.

The fact /etc/profile is now just completely gone means sometime between installing Go and this morning something else happened that deleted /etc/profile.

You need to wget the profile file from https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/profile and sudo copy to /etc/profile. Then $ exec bash and you should be good.

This is the first report of this occurring. If it happens again we will re-open and investigate further.

**Comment by aborruso** [comment]
Hi @sirredbeard I would like to do a WLinux update, but I have this problem.

I have dowloaded the `profile` file and run `$ exec bash profile`, but when I run it the windows close.

Is there some other tip?

**Comment by sirredbeard** [comment]
Why are you executing the profile file?

What are the contents of your profile file?

**Comment by aborruso** [comment]
@sirredbeard I'm really a newby.

Above you have written

> You need to wget the profile file from https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/master/linux_files/profile and sudo copy to /etc/profile. Then $ exec bash and you should be good.

I must run simply ` exec bash`? Is it good to do it in every folder? And than I can run wlinux-setup?

**Comment by MarcoBarna** [comment]
I have the same problem, i have installed zsh with wlinux-setup and the command(alias) dosen't work. I have checked and /etc/setup and /help are there and also the /etc/profile but neither bash nor zsh know the alias (can still use it by using /etc/setup though)

**Comment by kbrock84** [comment]
I had the same problem after running <code>omf destroy</code>

I ended up uninstalling wlinux. Rebooting and installing the app again.

Obviously that's not ideal, but it worked.

**Comment by kbrock84** [comment]
So this happened to me again. I think it may be starting with fish as the default terminal.

Workaround:
```bash

bash
cd /etc
source profile

```
Now try <code>wlinux-setup</code>

Worked for me

**Comment by bushidocodes** [comment]
New user. Just purchased and installed today. I had this same issue with zsh. It seems like once zsh is set as the default terminal, `/etc/profile` is never sourced. I'm going to revert to the approach that @kbrock84 suggested, but since `wlinux-setup` asked if I wanted to make zsh my default shell, I assume something misfired. I basically installed everything other than .NET and Powershell for Linux.

**Comment by sirredbeard** [comment]
So I looked at maybe 20 different ways of doing this.

zsh has 11 different config files loaded in different orders in different situations.

I looked at ln -s or cat/tee the existing /etc/profile into a couple of them or just dropping ``emulate sh -c 'source /etc/profile'`` into one but each one had it's own issue and none of them worked consistently.

In some cases zsh simply didn't run them or threw up errors because it doesn't like some of the massaging we do in /etc/profile for bash.

The solution that was consistent and error-free seems to be writing our own simple /etc/zsh/zshrc when zsh is installed.

See #187.

**Comment by Morgy93** [comment]
I am still having this issue - what do I need to do now to resolve it?

**Comment by cameronrye** [comment]
> I am still having this issue - what do I need to do now to resolve it?

Add this to your /etc/zsh/zshrc

```bash
export DISPLAY=:0
export LIBGL_ALWAYS_INDIRECT=1
export NO_AT_BRIDGE=1
alias wlinux-setup='bash /etc/setup'
alias wlinux-help='bash /etc/helpme'
```

**Comment by mikhailbalin** [comment]
Still the same issue

**Comment by tesurijp** [comment]
same issue.
