### ISSUE TITLE
Add pip

### ISSUE THREAD

**Issue by LemonAndroid** [WhitewaterFoundry/WLinux#12]

**Comment by sirredbeard** [comment]
Which pip package would you recommend?

**Comment by LemonAndroid** [comment]
It's weird it's not installed already.

> Python 2.7.9 and later (on the python2 series), and Python 3.4 and later include pip (pip3 for Python 3) by default.[5]

Other than that:
https://en.wikipedia.org/wiki/Pip_(package_manager)#Command-line_interface

**Comment by sirredbeard** [comment]
Hang on, this may actually have solved itself. If you are on the store version you are on 3.5, the upstream version is now shipping with 3.7 and I pulled in much more complete python environment (~100MB). Let me go check pip in my latest upstream build.

**Comment by LemonAndroid** [comment]
Hm, 3.5 should be sufficient, but the more complete python environment could have done the job already.

**Comment by LemonAndroid** [comment]
Why?

**Comment by sirredbeard** [comment]
Not everyone in the world has access to unlimited or fast bandwidth, so it is just something I am trying to be aware of and balance against big packages.

**Comment by LemonAndroid** [comment]
People paying 10-20 EUR for a WSL definitely have unlimited bandwidth.

**Comment by sirredbeard** [comment]
True. WLinux is discounted or free in developing countries.

I am going to see what kind of damage building with pip included does here in a few minutes.

**Comment by LemonAndroid** [comment]
I read about the free version. I'd do two different versions, because discounting or doing free by country is not preferable anyway imo. There's huge gaps on a national level.

**Comment by sirredbeard** [comment]
Yeah, it is not ideal. I do let people know they can DM on Twitter at @WLinuxApp if they cannot afford the price their market and I will make arrangements with them. I am building a new image with python3-pip enabled now to see how much bigger it makes the image. I agree pip is a big deal given the current popularity of python, the popularity of python among likely users of WLinux, frontend devs, and devops folks, and since we go out of our way to ship an upgraded python 3.7 we should probably include pip too.

**Comment by sirredbeard** [comment]
So I could ship python3-pip from stretch or testing in the image but then when I try to then autoupgrade pip in place with $ pip3 install --upgrade pip seems to then break pip:

```
hayden@t470s:~$ pip3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'
hayden@t470s:~$
```

I have always has issues in my own work with pip pip3 and so many different python versions, mismatches and such.

**Comment by LemonAndroid** [comment]
Don't use the apt package.

**Comment by sirredbeard** [comment]
What about [this](https://github.com/WhitewaterFoundry/WLinux/blob/master/linux_files/installpip3.sh), for now? 

If the script gets some interest and testing we can then consider applying to the default image. What do you think?

**Comment by LemonAndroid** [comment]
It's surreal. who wouldn't use pip with python? why package python in the default image w/o pip?

**Comment by sirredbeard** [comment]
I bring in a minimal python 3.7 from Debian testing, in part due to size concerns.

I would like to bring in pip from Debian testing too, to keep things simple, but that seems to bring in a lot of other packages. Also trying then trying to upgrade that pip using itself breaks it.

There is the install script, as you have pointed out, which is the official installation script.

But adding a script, particularly a python script, adds an extra layer of complexity to the image process.

So for the sake of prudence I would like to test the pip3 install script as a separate feature for a few days before then moving into the main image build process.

I hear you completely.

**Comment by LemonAndroid** [comment]
Oh ok, I understand. :)

**Comment by sirredbeard** [comment]
Pip is still in optional scripts and will probably not be shipped in default install **but** we are including it in a "python" mode with pip as requested in a new OOBE setup, see #36.

**Comment by LemonAndroid** [comment]
I feel like i wasted 10$. Not that big of a deal, I waste money on a regular basis but not having this stuff directly accessible puts a huge damper on the fun of using WLinux.

**Comment by sirredbeard** [comment]
See [here](https://github.com/WhitewaterFoundry/WLinux/issues/14#issuecomment-424485750).
