### ISSUE TITLE
Issues in explorer integration

### ISSUE THREAD

**Issue by LittleNewton** [WhitewaterFoundry/WLinux#219]
as shown in the graph
![1](https://user-images.githubusercontent.com/17793356/48929097-504cc300-ef20-11e8-8166-916044cfcf5c.png)

fail to install

![2](https://user-images.githubusercontent.com/17793356/48929099-52af1d00-ef20-11e8-8643-39ed4500ac83.png)

**Comment by patrick330602** [comment]
Thank you for the feedback. The bug is noted, and an emergency fix will come. 

Also, just some suggestions:
1. Please use the bug report template provided to report bugs;
2. This is an international project; please use English to report issue, there is a lot of people who do not understand Chinese.

**Comment by n3rd4i** [comment]
Same issue here:

**Describe the bug**
`screenfetch` hangs when called from command line.

**To Reproduce**
Steps to reproduce the behavior:
1. WLinux distribution installed
1. Run command: `wlinux-setup`
1. Select the following option:
	``` sh
	`[*] EXPLORER    Enable right-click on folders in Windows Explorer to open them in WLinux`
	```
4. See error: 
	``` sh
	Selected: EXPLORER
	EXPLORER
	Enabling Windows Explorer shell integration.
	Saving current directory as $CURDIR
	Going to $TMPDIR: /tmp/tmp.EnCvB6NK7h
	cp: cannot create regular file '/c/Users/andrei/AppData/Local/Temp'$'\r''/Install.reg': No such file or directory
	The operation completed successfully.
	Returning to /tmp/tmp.UudiBhxeO6
	Cleaning up /tmp/tmp.EnCvB6NK7h
	```

**Expected behavior**
`wlinux-setup` selection for `explorer integration` does not work properly.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[x] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[x] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the WLinux issues page: https://github.com/WhitewaterFoundry/WLinux/issues.
[x] I have reset WLinux: Settings->Apps->Apps & features->WLinux->Advanced Options->Reset. 
[x] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: `1.1.22.0`

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:

``` cmd
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18282 N/A Build 18282
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO*
```

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by n3rd4i** [comment]
Also tested on latest available version, behaviour is the same.

WLinux version: `1.1.25.0` (**1.1.25rc2** that is)

**Comment by crramirez** [comment]
Hello,

This error was corrected in the development branch, stay tunned

Regards

**Comment by sirredbeard** [comment]
Patched in #223 and pushed to master.

Please report back any issues.

**Comment by n3rd4i** [comment]
I can confirm that with the new update it seems to be **fixed**

**Comment by sirredbeard** [comment]
Yay! Thank you. And thank you @patrick330602 too.
