### ISSUE TITLE
Fastest way to set up PulseAudio?

### ISSUE THREAD

**Issue by MatejLach** [WhitewaterFoundry/WLinux#228]
What would be the fastest way to make PulseAudio work in WLinux? wlinux-setup does not offer the option to configure it, but I saw a closed pull request meant to incorporate it.  (https://github.com/WhitewaterFoundry/WLinux/pull/66). 

What is currently the fastest way to get PA working in both WSL and Windows? 
Thanks.

**Comment by sirredbeard** [comment]
https://token2shell.com/howto/x410/enabling-sound-in-wsl-ubuntu-let-it-sing/

https://research.wmz.ninja/articles/2017/11/setting-up-wsl-with-graphics-and-audio.html

Good luck.

**Comment by MatejLach** [comment]
@sirredbeard Yeah, I found these too, I just wanted to know that there isn't an "official" way to do it in wlinux, using ie wlinux-setup before I ventured further. 

Thanks for the clarification.

**Comment by jasonsbarr** [comment]
Ordinarily I wouldn't comment in an issue thread with over a year since its last activity, but this is high enough in the search results for various queries involving WSL and audio that I thought my experience might be helpful for someone else.

First, the tutorials linked above suggest using `localhost` as the address for your PulseAudio server. This didn't work for me; I had to get the IP for the Windows host with the following in my bash script:

```
 win_ip=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')
```

It's saved as a variable because I also use it for `DISPLAY`.

Export like so:
```
export PULSE_SERVER=tcp:${win_ip}
```

On line 61 of `\etc\pulse\default.pa` in the Windows PulseAudio package I had to combine information from both the above linked articles:
```
load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```

Finally, I had to compile my own version of the `pulseaudio` package on Pengwin using the source code from version 13.0 on the PulseAudio website, following the directions from the 2nd article above. That article suggests using version 8.0, but that wouldn't work for me due to dependency issues. 13.0 worked just fine.

Then everything was great... well, after I remembered that I needed to flip the switch on my wireless headset. 😂 

Hopefully that's helpful to someone else who may come along with the same issues I had.
