### ISSUE TITLE
Running a dockerized GUI in WLinux

### ISSUE THREAD

**Issue by beingbrown** [WhitewaterFoundry/WLinux#299]
This isn't really an issue--just something I'm trying to accomplish and failing miserably at. I've got a GUI app to successfully run from the wLinux subsystem (namely fcitx-config-gtk3), but now I'm trying to get proof of concept on running a dockerized GUI, and getting the following:

```
$ docker build -t test-gui .
$ docker run --env="DISPLAY" test-gui xeyes
Error: Can't open display: :0
```

I've tried a few different attempts at DISPLAY, which is where I figure the error is--I think it's mapping to the dockerfile's display :0, so I've set DISPLAY to $wslip:0.0, but I've gotten the same thing.

Here's the most recent version of the Dockerfile in question:

```
FROM debian:jessie
RUN apt-get update && apt-get install -y x11-apps
CMD
```

Any help would be greatly appreciated.

**Comment by crramirez** [comment]
Hello

You need to share a volume also with the authentication data or something
like this. Give me this week to figure out, and I'll post here the
solution.

Regards

**Comment by crramirez** [comment]
Hello,

Be sure that you are using [VCXSrv](https://sourceforge.net/projects/vcxsrv/) which listens to all interfaces and not only localhost. I need to figure out how to do it with X410, I think that xming will work also.

Execute from WLinux:

`docker run --env="DISPLAY=$(hostname):0.0" --rm test-gui xeyes`

if it doesn't work replace $(hostname) with your IP address (not localhost or 127.0.0.1). `--rm` will delete the container upon xeyes exit this is optional.

Regards

**Comment by beingbrown** [comment]
Hey @crramirez I appreciate the update. It looks like the problem may be associated with X410 then. I'll try a little experimentation and scour their documentation--and if you find something I'd love to know about it. If it doesn't work, I'll look into other xServers to pivot to (though I'd really like not to).

**Comment by crramirez** [comment]
People from X410 answered my support question, I will post it in a while if they give me permission. Meanwhile test with it:

`docker run --env="DISPLAY=docker.for.win.localhost:0.0" --rm test-gui xeyes` with X410

(to close the eyes hit Alt+F4)

**Comment by beingbrown** [comment]
Awesome! thanks @crramirez I'm able to get eyes now, which makes me feel more comfortable to move to more complicated apps (firefox is next). Thanks for reaching out to them--I also sent a support ticket, but haven't heard back yet. I'm not able to close the eyes with Alt+F4, but I can do it just by closing with X in the taskbar. I'd love a way to Ctrl+C to kill, but I also suspect I can kill with a docker command.

**Comment by crramirez** [comment]
Excellent!! Here their answer:


> I am trying to make a remote connection. A GUI application running in 
> Hyper-V. When I try to launch it I get "Error: Can't open display: 
> myipaddress:0.0". I noticed that X410 only listens in 127.0.0.1 there 
> is any way to make it listen on all interfaces?

You're correct. Due to security concerns, X410 is currently accepting 
connections only for 127.0.0.1. We'll eventually add an option to allow 
other local addresses but at the moment it's locked down.

For your information, some virtual machine related products have a 
special address that can be used for connecting to the loopback 
interface (ex. 127.0.0.1) on their host. For example, you can use 
"DISPLAY=docker.for.win.localhost:0.0" to connect to X410 from a 
container in Docker for Windows. We're not sure such feature exists for 
Hyper-V, but there is a workaround. You can create a relay socket using 
the Windows built-in command "netsh" 
(https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy).

For example, if your computer's address is 172.18.30.225, you can use 
the following command (as administrator) and add a relay socket:

netsh interface portproxy add v4tov4 listenaddress=172.18.30.225 
listenport=6000 connectaddress=127.0.0.1 connectport=6000 protocol=tcp

6000 is the default port number for X servers and it's equivalent to 
DISPLAY= 172.18.30.225:0.0. If you change it to 6001, the DISPLAY 
becomes 192.168.1.67:1.0 and so forth.

Once it's set up, you can use "export DISPLAY=172.18.30.225:0.0" from 
your remote server (without any SSH X11 forwarding) to access X410 at 
127.0.0.1:0.0.

Windows seems to maintain relay sockets even after the reboot. So when 
you no longer need the socket, you can use the following command to 
delete it:

netsh interface portproxy delete v4tov4 listenaddress=172.18.30.225 
listenport=6000

To see the currently added relay sockets:

netsh interface portproxy show all

Hope this helps.

Best regards,
Support Team (support@choung.net)
Choung Networks | http://choung.net/

**Comment by beingbrown** [comment]
Hey, I'm going to close this now. Thanks so much for your active engagement on something that wasn't even an issue. definitely reinforces that I'm glad I bought the product (and also that I wasn't crazy with my initial attempts).

**Comment by crramirez** [comment]
You are welcome. This is what we want, that WSL be more useful and usable for everyone. I must admit that I saw a challenge in your proposal and I wanted making it run in X410 too
