### ISSUE TITLE
Support chromium for WSL

### ISSUE THREAD

**Issue by LucasYihsuehTsai** [WhitewaterFoundry/WLinux#319]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LucasYihsuehTsai** [comment]
Chrome doesn't work with WSL

**Comment by crramirez** [comment]
Hello,

Yes and probably it would require a lot of work. My question is. Is it worth? Give me some reasons why someone would need to run Chromium in WSL. I am sincerely asking. 

Regards

**Comment by ThatWeirdAndrew** [comment]
My personal opinion is that it would take too much time and effort to support this due to the current limitations of WSL. One reason why this isn't high on anyone's priority list is that you can just install the latest chromium build on windows here: https://download-chromium.appspot.com/. However, I am open to hearing why you think that we should support chromium.

**Comment by crramirez** [comment]
Hello,

I installed chromium using `apt install chromium` and ran using: `sudo chromium --no-sandbox` it worked.

Some considerations:

1. I installed VS Code using wlinux-setup
2. Disabled OpenGL indirect rendering: `export -n LIBGL_ALWAYS_INDIRECT`

Test and post here if you were able to run it as well

Regards

**Comment by LucasYihsuehTsai** [comment]
Thanks

**Comment by LucasYihsuehTsai** [comment]
Test result:

![image](https://user-images.githubusercontent.com/47374878/53384556-466eac00-39b6-11e9-9f9e-b0ffd7acb918.png)

**Comment by crramirez** [comment]
Wiiiiii!!!! Enjoy
