### ISSUE TITLE
Support spyder3 for WSL

### ISSUE THREAD

**Issue by LucasYihsuehTsai** [WhitewaterFoundry/WLinux#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crramirez** [comment]
Hello,

Currently spyder3 doesn't run in WSL? Or you are asking for an automated installer for Anaconda and then spyder3? 

Regards

**Comment by DarthSpock** [comment]
@crramirez Anaconda already comes with Spyder, Jupyter, etc. Minconda on the other hand does not. From my experience with it, Miniconda is a better option due to the package management system downgrading packages due to dependencies. To maintain the most current version of packages installed with conda is best achieved (but not guaranteed) through the minimal installation option (Miniconda). If you wanted to add Spyder as a sub-option to Miniconda in wlinux-setup using `conda install spyder,` I think that would meet this request. But it's a trivial thing to simply run `conda install ...` after wlinux-setup since you'll need to run `conda upgrade ...` on a normal basis anyways. Plus I think both the python2 and python3 versions of Miniconda would need to available and prompt the user to choose one (you can only install one or the other).

**Comment by sirredbeard** [comment]
spyder3 is packaged for Debian but I agree the Anaconda distribution is usually better maintained. I have not tried miniconda.

**Comment by DarthSpock** [comment]
> I have not tried miniconda.

They're the same thing, only one as I stated comes with bare conda and python. Anaconda comes with all the features, whether you need them all or not and takes up much more disk space. Install obviously would go faster as well since less data to be downloaded. 

For reference: https://docs.conda.io/en/latest/miniconda.html

**Comment by LucasYihsuehTsai** [comment]
When I try to run spyder3, I got following messages.  

~$ spyder3
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-lucas'
Unrecognized OpenGL version
Unrecognized OpenGL version
shared memfd open() failed: Function not implemented
[10:37:0207/110643.672299:FATAL:udev_linux.cc(34)] Check failed: 0 == ret (0 vs. -22)
#0 0x7f43456eb52f <unknown>
#1 0x7f4345706a4c <unknown>
#2 0x7f4344598072 <unknown>
#3 0x7f4344596c11 <unknown>
#4 0x7f43456ebc39 <unknown>
#5 0x7f434570d6e0 <unknown>
#6 0x7f434570e13d <unknown>
#7 0x7f434570e427 <unknown>
#8 0x7f4345710881 <unknown>
#9 0x7f43457301cf <unknown>
#10 0x7f4344864aeb <unknown>
#11 0x7f4344864f9b <unknown>
#12 0x7f4345753ed8 <unknown>
#13 0x7f434574f280 <unknown>
#14 0x7f435d816fa3 <unknown>
#15 0x7f435d3197ef <unknown>

Received signal 6
#0 0x7f43456eb52f <unknown>
#1 0x7f434411cb1d <unknown>
#2 0x7f43456eba3e <unknown>
#3 0x7f435d821670 <unknown>
#4 0x7f435d25785b <unknown>
#5 0x7f435d242535 <unknown>
#6 0x7f43456e9fa9 <unknown>
#7 0x7f4345706b9f <unknown>
#8 0x7f4344598072 <unknown>
#9 0x7f4344596c11 <unknown>
#10 0x7f43456ebc39 <unknown>
#11 0x7f434570d6e0 <unknown>
#12 0x7f434570e13d <unknown>
#13 0x7f434570e427 <unknown>
#14 0x7f4345710881 <unknown>
#15 0x7f43457301cf <unknown>
#16 0x7f4344864aeb <unknown>
#17 0x7f4344864f9b <unknown>
#18 0x7f4345753ed8 <unknown>
#19 0x7f434574f280 <unknown>
#20 0x7f435d816fa3 <unknown>
#21 0x7f435d3197ef <unknown>
  r8: 0000000000000000  r9: 00007f431179eb20 r10: 0000000000000008 r11: 0000000000000008
 r12: 00007f435b942d40 r13: 00007f431179efd0 r14: 0000000000000055 r15: 00007f435b942080
  di: 0000000000000002  si: 00007f431179eb20  bp: 00007f431179ed70  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000008  sp: 00007f431179eb20
  ip: 00007f435d25785b efl: 0000000000000246 cgf: 00000053002b0033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by crramirez** [comment]
Install Visual Studio Code from wlinux-setup it have  a fix for this issue. If it is the problem we can include the fix for the next wlinux-setup version.

**Comment by LucasYihsuehTsai** [comment]
I can install miniconda using the following step, thanks
sudo apt-get -y install bzip2
bash Miniconda3-latest-Linux-x86_64.sh
