### ISSUE TITLE
Assistance installing Python on 1.1.17

### ISSUE THREAD

**Issue by aborruso** [WhitewaterFoundry/WLinux#77]
Hi,
everything I install with pip3 gives me `-bash: ipython: command not found`.

In example after installing ipython with `pip3 install ipython`.

**WLinux Version**

Find: Settings->Apps->Apps & features->WLinux->Advanced Options->Version.

Insert here: 1.1.17.0

**Windows Build**

10.0.17134.285

![image](https://user-images.githubusercontent.com/30607/46262409-27501900-c501-11e8-9566-bfc7633d20b1.png)

**Comment by sirredbeard** [comment]
So about that.

First, packaging python with all it's various versions and add-ons is tough. We took an early stab at shipping python 3.7 from testing on WLinux with 1.1.15 and it caused issues with build-essential, so we are trying to get this right.

There is a reason that Anaconda and Azure-cli ship with their own internal python, because it is dependency mess. We beg your patience and know supporting python is important.

The good news is that we have a new setup script coming in 1.1.20 which was submitted to the Microsoft Store today that sets up python, IDLE, and pip nicely for new users.

I would recommend re-installing once that becomes available.

Alternatively you can reset WLinux now and then run this upgrade with this handy script: https://gist.github.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f

From the terminal:
`$ curl -L https://gist.githubusercontent.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f/raw/f996ad9a37936ceace1e5a84692a90c830fcb6f9/upgradewlinux.sh | bash`

Going forward, after 1.1.20, you will always be able to update to the latest setup script by running` $ bash /etc/setup`.

**Comment by aborruso** [comment]
@sirredbeard I have tried,

> I would recommend re-installing once that becomes available.
> 
> Alternatively you can reset WLinux now and then run this upgrade with this handy script: https://gist.github.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f
> 
> From the terminal:
> $ curl -L https://gist.githubusercontent.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f/raw/f996ad9a37936ceace1e5a84692a90c830fcb6f9/upgradewlinux.sh | bash

but I have had

```
cp: cannot stat '/ShellIntegration/*': No such file or directory
cp: cannot stat '/linux_files/setup': No such file or directory
cp: cannot stat '/linux_files/profile': No such file or directory
WLinux will now close. Please re-open and the updated script will begin.
```

**Comment by sirredbeard** [comment]
Try again.

https://gist.github.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f

`$ curl -L https://gist.githubusercontent.com/sirredbeard/2324e665e4d6162298dd42dd646ff92f/raw/98411dd4cfdf277ffb9ea0b35be1c29524cfdb8f/upgradewlinux.sh | bash`

**Comment by aborruso** [comment]
the same

```
Cloning into 'WLinux'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1894 (delta 15), reused 2 (delta 0), pack-reused 1864
Receiving objects: 100% (1894/1894), 2.78 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (1072/1072), done.
mkdir: cannot create directory ‘/opt/ShellIntegration’: File exists
WLinux will now close. Please re-open and the updated script will begin.
```

**Comment by sirredbeard** [comment]
When you re-open nothing happens?

Run `$ bash /etc/setup`

**Comment by sirredbeard** [comment]
It should automatically re-run the script, regardless of your shell. But something is funky with your install. I am sorry for all the trouble.

I would recommend just tinkering for now and then reinstalling a fresh version of 1.1.20 when it is released, likely available within 12-24 hours.

**Comment by aborruso** [comment]
ok thank you

How to uninstall it? From Windows Apps panel?

**Comment by sirredbeard** [comment]
Yes, just like you would any other Windows app from the store. You can even go into Advanced Options under Apps and do a Reset, which will reset your data and download the latest version. I cannot predict but I expect 1.1.20 to be available sometime in next 12-24 hours. Thank you for your patience.
